# Replace the text below to customize your site
site_name: Carolina Almeida
site_description: Master in Design for Emergent Futures
site_author: Carolina Almeida
copyright: Copyleft 2021 "Carolina Almeida" - GNU Free Documentation License
repo_name: 'Carolina Almeida: Github Repo'
site_url: https://fablabbcn.github.io/mdef-template/
repo_url: 'https://github.com/fablabbcn/mdef-template'


nav:
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
  - Reflections:
      - Term 1:
          - Design Studio I:
            - Communication Strategy: term1/designstudio/communication.md
            - RtD: term1/designstudio/research-through-design.md
          - Bootcamp:
            - Poster: term1/bootcamp/01-Bootcamp.md
            - Vision: term1/bootcamp/vision.md
          - AoWS:
            - Card Experiment: term1/aws/02-Atlas of Weak Signals.md
            - Design Space: term1/aws/design-space.md
            - Map of Resources: term1/aws/map-of-resources.md
          - Bio & Agri Zero:
            - Theory: term1/bio&agrizero/theoryweek1.md
            - Lab Notes: term1/bio&agrizero/labnotes.md
            - Assignments: term1/bio&agrizero/assignments.md
          - Living With Your Ideas:
              - LWYI - Clay Tablet: term1/lwyi/01-lwyi.md
              - Companion: term1/lwyi/02-lwyi.md
          - Tech Beyond the Myth:
                  - Undoing Design's Black Box: term1/tech/techbeyondthemyth.md
                  - From Coffee to Bubbles: term1/tech/fromcoffeetobubbles.md
          - Community Engagement:
                  - Mapping and Facilitating: term1/communityengagement/community1.md
          - Extended Intelligences:
                  - Reflections: term1/extended/reflect.md
                  - Conceptualizing a thing: term1/extended/thing
      - Term 2:
          - The Next Billion Seconds: term2/billionseconds.md
          - Design Studio: 
            - Design space: term2/designstudio2/designspace2
          - Remixing Materials:
            - Assignments: term2/remixmaterials/assignment.md
            - Material Explorations: term2/remixmaterials/reflections








extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_carol__almeida_/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/in/carolina-almeida-36014718b/"
    - icon: fontawesome/brands/github
      link: "https://github.com/"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: black
  font:
    # See available fonts at https://fonts.google.com/
    text: Crimson Text
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
